/* Generated By:JavaCC: Do not edit this line. languageConstants.java */
package labP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface languageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int False = 5;
  /** RegularExpression Id. */
  int WORD = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int SIGN = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int Equal = 10;
  /** RegularExpression Id. */
  int assign = 11;
  /** RegularExpression Id. */
  int And = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int Do = 17;
  /** RegularExpression Id. */
  int SEMI = 18;
  /** RegularExpression Id. */
  int OpenB = 19;
  /** RegularExpression Id. */
  int CloseB = 20;
  /** RegularExpression Id. */
  int Skip = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"ff\"",
    "<WORD>",
    "<NUMBER>",
    "<SIGN>",
    "\"!\"",
    "\"==\"",
    "\":=\"",
    "\"^\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"skip\"",
    "\"tt\"",
  };

}
